config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  get '/general_shopping_list', to: 'recipe_foods#index', as: 'shopping_list'
  resources :foods, only: %i[index show create destroy]
  resources :recipes, only: %i[index show create update destroy]
  resources :recipe_foods, only: %i[create destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/views/layouts/shared/_ingredient_form_html.erb
<%= form_with(model: recipe_food) do |form| %>
    <% if recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>
  
        <ul>
          <% recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.hidden_field :recipe_id, value: @recipe.id %>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %> <br>
    <%= form.label :food, class: 'form-label' %>
    <%= form.text_field :food, class: 'form-control', list: "datalistOptions", placeholder: "Type to search owned ingredients..." %>
    <datalist id="datalistOptions">
    <% if current_user.present? %>
      <% current_user.foods.each do |food| %>
        <option value="<%= food.name %>">
    <% end %>
      <% end %>
    </datalist>
    <%= form.label :measurement_unit, class: 'form-label' %>
    <%= form.text_field :measurement_unit %> <br>
    <%= form.label :price, class: 'form-label' %>
    <%= form.text_field :price %> <br>
    <div>
      <%= form.submit class: 'btn btn-primary mt-3' %>
    </div>
  <% end %>

app/views/layouts/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Recipes on Rails</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href=<%= root_path %>>Home</a>
          <a class="nav-link" href=<%= public_recipes_path %>>Public Recipes</a>
        </div>
        <div class="nav-buttons ms-auto d-flex align-items-baseline">
          <% if current_user.present? %>
            <div class="btn-group">
              <button
                type="button"
                class="btn btn-outline dropdown-toggle me-3"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Welcome,
              <%= current_user.name %>
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href=<%= recipes_path %>>My Recipes</a></li>
                <li><a class="dropdown-item" href=<%= foods_path %>>My Inventory</a></li>
                <li><a class="dropdown-item" href=<%= shopping_list_path %>>Generate Shopping List</a></li>                
              </ul>
            </div>            
            <%= button_to(
              "Log Out",
              destroy_user_session_path,
              method: :delete,
              class: "btn btn-primary"
            ) %>
          <% else %>
            <a class="nav-item btn btn-primary me-2" href=<%= user_session_path %>>Log in</a>
            <a class="nav-item btn btn-secondary" href=<%= new_user_registration_path %>>Sign up</a>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>