config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  get '/general_shopping_list', to: 'recipe_foods#index', as: 'shopping_list'
  resources :foods, only: %i[index show create destroy]
  resources :recipes, only: %i[index show create update destroy]
  resources :recipe_foods, only: %i[create destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  validates :name, presence: true, length: { in: 2..250 }
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  scope :recent_recipes, -> { Recipe.where(public: true).last(5) }

  def self.sum_ingredients(user_id)
    recipes = User.find(user_id).recipes
    ingredients = {}
    recipes.each do |recipe|
      recipe.recipe_foods.includes(:food).each do |ingredient|
        if ingredients.key?(ingredient.food.name)
          ingredients[ingredient.food.name] += ingredient.quantity
        else
          ingredients[ingredient.food.name] = ingredient.quantity
        end
      end
    end
    ingredients
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show update destroy]
  before_action :authenticate_user!, except: %i[public_recipes show]
  authorize_resource except: :public_recipes

  def index
    user = current_user
    @recipes = user.recipes.order(created_at: :desc)
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).includes(:user)
  end

  def show
    @ingredients_list = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |f|
      if @recipe.save
        f.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
      else
        f.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
    <% if recipe.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
  
        <ul>
          <% recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="my-1">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div class="my-1">
      <%= form.label :preparation_time, style: "display: block" %>
      <%= form.time_field :preparation_time %>
    </div>
  
    <div class="my-1">
      <%= form.label :cooking_time, style: "display: block" %>
      <%= form.time_field :cooking_time %>
    </div>
  
    <div class="my-1">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, class: 'w-100' %>
    </div>
  
    <div class="form-check form-switch my-1">
      <%= form.label :public, class: "form-check-label" %>
      <%= form.check_box :public, class: "form-check-input", role: "switch" %>
    </div>
  
    <div>
      <%= form.submit class: 'btn btn-primary mt-2' %>
    </div>
  <% end %>

app/views/recipes/_recipe.html.erb
<div class="row px-3" id="<%= dom_id recipe %>">
  <div class="col-5 ml-2 d-flex flex-column align-items-center justify-content-around"  style="height: 7rem;">
    <h4><%= recipe.name %></h4>
    <% if can? :destroy, recipe %>
      <%= button_to "REMOVE", recipe, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>

  <div class="col-7">
    <p><%= recipe.description %></p>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="d-flex flex-column align-items-center mx-5 my-2" id="recipes">
  <h1 class="align-self-start">Recipes</h1>
  <button
    type="button"
    class="btn btn-primary mb-4"
    data-bs-toggle="modal"
    data-bs-target="#recipesModal"
  >
    New Recipe
  </button>
  <% @recipes.each do |recipe| %>
    <%= link_to recipe, class: 'card mb-4 p-2 border-dark overflow-hidden', style: 'height: 8.5rem; text-decoration: none; color: black; width: 60%' do %>
      <%= render recipe %>
    <% end %>
  <% end %>
</div>

<div class="modal" tabindex="-1" id="recipesModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New recipe</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <%= render "form", recipe: Recipe.new %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="public-recipes d-flex flex-column align-items-center mx-5 my-2">
  <h1 class="align-self-start">Public Recipes</h1>
  <% if can? :create, Recipe %>
    <button
      type="button"
      class="btn btn-primary mb-4"
      data-bs-toggle="modal"
      data-bs-target="#recipesModal"
    >
      New Recipe
    </button>
  <% end %>
  <% @public_recipes.each do |recipe| %>
    <%= link_to recipe, class: 'card mb-4 p-2 border-dark overflow-hidden', style: 'height: 7rem; width: 50%; text-decoration: none; color: black;' do %>
      <div class="row px-3" id="<%= dom_id recipe %>">
        <div
          class="
            col-5
            ml-2
            d-flex
            flex-column
            align-items-center
            justify-content-around
          "
          style="height: 7rem;"
        >
          <h4><%= recipe.name %></h4>
          <p class="d-flex flex-column align-items-start">By:
            <%= recipe.user.name %></p>
        </div>
        <div class="col-7 d-flex flex-column align-items-center justify-content-around">
          <p>Total food items:
            <%= recipe.recipe_foods.count %></p>
          <p>Total price: $<%= recipe_total_value(recipe) %></p>
        </div>
      </div>

    <% end %>
  <% end %>
</div>

<% if can? :create, Recipe %>
  <div class="modal" tabindex="-1" id="recipesModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">New recipe</h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <%= render "form", recipe: Recipe.new %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/show.html.erb
<section class="container border border-dark py-3">
  <div class="row">
    <h3 class="d-flex flex-column align-items-center mb-3"><%= @recipe.name %></h3>
    <div class="col-9">
      <p>
        <strong>Preparation Time:</strong>
        <%= @recipe.preparation_time.strftime("%Hhrs %Mmin") %>
      </p>
      <p>
        <strong>Cooking Time:</strong>
        <%= @recipe.cooking_time.strftime("%Hhrs %Mmin") %>
      </p>
    </div>
    <div class="col-3">
      <%= form_with url: recipe_path, method: :put, scope: :recipe do |form| %>
        <% if can? :update, @recipe %>
          <div class="form-check form-switch">
            <%= form.label :public, class: "form-check-label" %>
            <%= form.check_box :public,
                           {
                             class: "form-check-input",
                             role: "switch",
                             onchange: "this.form.submit()"
                           } %>
          </div>
        <% end %>
      <% end %>
    </div>
    <p><%= @recipe.description %></p>
  </div>
  <% if current_user.present? %>
    <div class="d-flex justify-content-between">
      <%= link_to "Go to shopping list",
      shopping_list_path,
      class: "btn btn-secondary mb-4" %>
    <% end %>
    <% if can? :update, @recipe %>
      <button
        type="button"
        class="btn btn-secondary mb-4"
        data-bs-toggle="modal"
        data-bs-target="#ingredientsModal"
      >
        Add Ingredient
      </button>
    <% end %>
  </div>
  <hr class="hr"/>
  <table class="table table-striped table-hover table-bordered table-sortable">
    <thead>
      <tr>
        <th>Ingredient</th>
        <th>Quantity</th>
        <th>value</th>
        <% if can? :update, @recipe %>
          <th>Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @ingredients_list.each do |ingredient| %>
        <tr>
          <td><%= ingredient.food.name %></td>
          <td><%= ingredient.quantity %></td>
          <td>$<%= ingredient.food.price * ingredient.quantity %></td>
          <% if can? :update, @recipe %>
            <td>
              <%= button_to "Delete", ingredient, method: :delete, class: "btn btn-danger" %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if can? :update, @recipe %>
    <div class="modal" tabindex="-1" id="ingredientsModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">New Ingredient for
              <%= @recipe.name %></h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body">
            <%= render "shared/ingredient_form", recipe_food: RecipeFood.new %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</section>